version: '3'

volumes:
  mongo-data:

networks:
  voc-net:
    driver: bridge

services:

  server:
    build:
      dockerfile: ./Dockerfile
      context: .
    depends_on:
      - "db"
      - "search"
    ports:
      - "8080:8080"
      - "443:443"
    restart: on-failure
    networks: 
      - voc-net
    volumes:
      - ./:/vocserver
      - ./config/search_setup.sh:/initsearch.d/init.sh
    command: sh -c "cd vocserver && ./config/search_setup.sh &&
              java -jar target/vocserver-1.0-fat.jar -conf config/vocserver.json"
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"

  server-local:
    build:
      dockerfile: ./Dockerfile
      context: .
    depends_on:
      - "db"
    ports:
      - "443:443"
      - "8081:8081"
    restart: on-failure
    networks: 
      - voc-net
    volumes:
      - ./:/vocserver
    command: sh -c "cd vocserver && ./redeploy.sh"
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"

  db:
    image: mongo
    volumes:
      - mongo-data:/var/lib/mongodb/
      - ./config/mongo_setup.sh:/docker-entrypoint-initdb.d/init.sh
      - ./config/vocserver.json:/docker-entrypoint-initdb.d/vocserver.json
    networks: 
      - voc-net
    expose:
      - "27017"
    command: mongod --auth
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
  db-local:
    image: mongo
    volumes:
      - mongo-data:/var/lib/mongodb/
      - ./config/mongo_setup.sh:/docker-entrypoint-initdb.d/init.sh
      - ./config/vocserver_local.json:/docker-entrypoint-initdb.d/vocserver.json
    networks: 
      - voc-net
    ports:
      - "27017:27017"
    command: mongod --auth
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
  
  search:
    image: getmeili/meilisearch
    networks: 
      - voc-net
    expose:
      - "27017"
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m" 
